version: '3'

services:
  postgres:
    image: postgres:15.4
    restart: always
    env_file:
      - postgres.dev.env
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
